apiVersion: v1
kind: Service
metadata:
  name: {{ include "sovereign-ai-gateway.fullname" . }}-litellm
  labels:
    app.kubernetes.io/name: {{ include "sovereign-ai-gateway.name" . }}-litellm
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ if .Values.litellm.service }}{{ default "ClusterIP" .Values.litellm.service.type }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ if .Values.litellm.service }}{{ default 4000 .Values.litellm.service.port }}{{ else }}4000{{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sovereign-ai-gateway.name" . }}-litellm
    app.kubernetes.io/instance: {{ .Release.Name }}
