{{- range .Values.backends }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sovereign-ai-gateway.fullname" $ }}-vllm-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "sovereign-ai-gateway.name" $ }}-vllm-{{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sovereign-ai-gateway.name" $ }}-vllm-{{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
