{{- range .Values.backends }}
{{- if .persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sovereign-ai-gateway.fullname" $ }}-vllm-cache-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "sovereign-ai-gateway.name" $ }}-vllm-{{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  accessModes:
    - {{ .persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .persistence.size | quote }}
  {{- if .persistence.storageClass }}
  {{- if (eq "-" .persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
